# ============================================================
# RESTOR-PC Boot Manager
# ============================================================

timeout 8

use_graphics_for windows,linux
resolution 1920 1080

hideui hints,arrows,badges
scanfor manual

include themes/restor-pc/theme.conf

menuentry "WIN CODE" {
    icon \EFI\BOOT\themes\restor-pc\assets\win_code.png
    volume "CODE-EFI"
    loader \EFI\Microsoft\Boot\bootmgfw.efi
    ostype Windows
}

menuentry "WIN VESTY" {
    icon \EFI\BOOT\themes\restor-pc\assets\win_vesty.png
    volume "VESTY-EFI"
    loader \EFI\Microsoft\Boot\bootmgfw.efi
    ostype Windows
}

menuentry "MEMTEST86+" {
    icon \EFI\BOOT\themes\restor-pc\assets\memtest86plus.png
    loader \EFI\TOOLS\MEMTEST\mt86plus.efi
}
