# Restor-PC Boot Manager - configuration rEFInd
timeout 8
use_graphics_for windows,linux
resolution 1920 1080
hideui hints,arrows,label,badges
icons_dir icons

# Recherche les chargeurs EFI internes et externes. Les entrées Linux ajoutées
# ultérieurement seront détectées automatiquement.
scanfor internal,external,manual
also_scan_dirs EFI/Microsoft/Boot,EFI/ubuntu,EFI/Linux
dont_scan_files shim.efi,MokManager.efi,mmx64.efi,fbx64.efi,BOOTX64.EFI,refind_x64.efi

# Thème Restor-PC
include themes/restor-pc/theme.conf
